# Generated by Django 6.1 on 2026-08-31 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['current_state', 'priority', 'created_at'], name='task_delive_current_0c07f9_idx'),
        ),
    ]
